server:
  port: 8080

spring:
  application:
    name: spring-boot4-test
  profiles:
    active: prod
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/starfish?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: 123456789

# minio
starfish:
  minio:
    enabled: true
    endpoint: https://sunkolin.xyz:9000
    access-key: yLYYn14VnYcdLyOnOY12
    secret-key: OZGbQ31lTGptvH1Io6Wc5wfKfwvMxuQvuOZA3TtZ
    bucket-name: my-bucket-dev
    expire: 3600
